### ISSUE TITLE
手機測試後修改

### ISSUE THREAD

**Issue by jungleft** [jungleft/jungho#15]
卡關：
嘗試修改網頁名稱和icon，名稱找不到在哪修改，icon已修改。
首頁的link改為文字了，但是無法調整大小。

想修改：
點進相簿時，希望左邊的link欄位跟投稿頁面時一樣。
手機塗鴉的圖在首頁會很大，電腦則是很小，希望能相同比例。
首頁圖會一整坨一起移動，希望能分開一些。

**Comment by bestian** [comment]
Split into some issues~
